AllCops:
  TargetRubyVersion: 2.6.0
  DisplayCopNames: true

Naming/AccessorMethodName:
  Description: Check the naming of accessor methods for get_/set_.
  Enabled: false

Style/DocumentationMethod:
  RequireForNonPublicMethods: false

Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 30

Style/SymbolArray:
  Enabled: true
  EnforcedStyle: brackets

Style/StringLiterals:
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
