---
language: ruby
sudo: false
cache: bundler
rvm:
  - 2.6.2
before_install: gem install bundler
script: bundle exec rspec spec
notifications:
  email:
    - imamatory@gmail.com
after_success:
- CI=true TRAVIS=true coveralls --verbose
